# Generated by Django 4.1.5 on 2023-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=1500)),
                ('news_posted_by', models.CharField(max_length=1500)),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('news_about', models.CharField(max_length=1500)),
                ('news_image', models.ImageField(blank=True, upload_to='news_images/')),
                ('news_comments_count', models.IntegerField()),
            ],
        ),
    ]
