# Generated by Django 4.1.5 on 2023-01-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('item_decsp', models.TextField(max_length=5000)),
                ('item_price', models.CharField(max_length=500)),
                ('item_cover_pic', models.ImageField(blank=True, upload_to='Food_Products/images')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categorymain')),
            ],
        ),
    ]
